name: NutriWise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  flutter_screenutil: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/banner.jpg
    - assets/profile.jpg
    - assets/apple.jpg # remove
    - assets/logo.png
    - assets/login_bg.jpg
    # Categories
    - assets/categories/Beverages/beverages.jpg
    - assets/categories/Snacks/snacks.jpg
    - assets/categories/Dairy/dairy.jpg
    - assets/categories/Staples/staples.jpg
    - assets/categories/Canned/canned.jpg
    # Featured
    - assets/featured/rxbar.jpeg
    - assets/featured/bulletproof.jpg
    - assets/featured/blackbean.jpg
    - assets/featured/beehive.jpg
    # Seasonal
    - assets/seasonal/califia.png
    - assets/seasonal/naturebox.jpg
    - assets/seasonal/siggis.jpg
    - assets/seasonal/tolerant.jpg

  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/YesevaOne-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
